// Generated by Copilot
// Activation functions for NEAT-RS

pub mod activation {
    /// Logistic sigmoid activation function
    pub fn logistic(x: f64, derivative: Option<bool>) -> f64 {
        if derivative.unwrap_or(false) {
            let fx = 1.0 / (1.0 + (-x).exp());
            fx * (1.0 - fx)
        } else {
            1.0 / (1.0 + (-x).exp())
        }
    }
}
