// Generated by Copilot
// Crossover methods for genetic algorithms

pub enum CrossoverMethod {
    SinglePoint { config: Option<f64> },
    TwoPoint { config: Option<(f64, f64)> },
    Uniform,
    Average,
}
