// Generated by Copilot
// Mutation methods for genetic algorithms

pub enum MutationMethod {
    AddNode,
    SubNode { keep_gates: bool },
    AddConn,
    SubConn,
    ModWeight { min: f64, max: f64 },
    ModBias { min: f64, max: f64 },
    ModActivation,
    AddSelfConn,
    SubSelfConn,
    AddGate,
    SubGate,
    AddBackConn,
    SubBackConn,
    SwapNodes,
}
