// Generated by Copilot
/**
 * CONFIG
 * @module config
 * Global configuration object for NEAT-TS
 * @property warnings - Enable/disable warnings
 */
const config: { warnings: boolean } = {
    warnings: false
};

export default config;
