// Generated by Copilot
/**
 * NEAT-TS main library entry point
 * @module index
 */

import architect from './architecture/architect';
import Connection from './architecture/connection';
import Group from './architecture/group';
import Layer from './architecture/layer';
import Network from './architecture/network';
import Node from './architecture/node';
import config from './config';
import methods from './methods/methods';
import multi from './multithreading/multi';
import Neat from './neat';

const NeatJS = {
  methods,
  Connection,
  architect,
  Network,
  config,
  Group,
  Layer,
  Node,
  Neat,
  multi,
};

export default NeatJS;
