// Generated by Copilot
/**
 * Jest configuration for TypeScript project
 * @see https://kulshekhar.github.io/ts-jest/docs/getting-started/configuration/
 */
export default {
    preset: 'ts-jest',
    testEnvironment: 'node',
    testMatch: ['**/test/**/*.test.ts']
};
